### ISSUE TITLE
ReportTweaks Edit screen not running on all projects?

### ISSUE THREAD

**Issue by jgardner-qha** [uwctri/ReportTweaks#8]
REDCap 12.5.9 PHP 7.4
ReportTweaks 1.2.0

Summary:
It seems that the additional UI features on Edit Report provided by the ReportTweaks module does not appear on all projects for which it has been enabled. After enabling the module, some of our projects display the options, and some of them do not. In many cases, it is the only module enabled for the project, or the same modules as other projects, so I don't think it is a conflict. The additional UI features do appear while viewing reports on all projects.

No errors or warnings appear in the browser's dev console. Looking at the source, I can see some javascript code and template tags, but the tr and div tags that provide the UI do not appear at all.

Any ideas? What additional steps can I do to troubleshoot this?

**Comment by aanunez** [comment]
Hello,

My production server is running 12.5.6 currently and I assume the problem here must be related to some layout changes the occurred in version 12.5.9. What I don't understand is why this would only be happening sometimes. 

If you'd like to troubleshoot yourself and report back then the two important js lines are
`
let reportOpt = $("input[name=filter_type]").closest('tr').prevAll().eq(2);
reportOpt.next().after(reportOpt.prev().nextAll(':lt(2)').addBack().clone().addClass('reportTweaks'));
`
The first line should select the title area of the box "Additional report options (optional)". The second line inserts a modified duplicate after that box. I assume that the name of the input I used to find the box in the dom must have changed. 

For a long term fix I will need a few days, when I have free time I will update my dev server to 12.5.10 and investigate this issue along with issue #7

**Comment by jgardner-qha** [comment]
Aha, that makes sense why it only appears for some projects. That field ( input name=filter_type checkbox ) exists only on a longitudinal project or a project with repeating instances. Not all of my projects have repeating instances, but some of the report tweaks would still be useful!

I'm not well versed in git (or javascript, for that matter), but I'll see if I can do a PR with a potential fix. I'll leave the other issue to you, though... 🙂

Thanks so much for your work on this module. It adds several highly desired features to REDCap reports. Perhaps one day they'll get into core?


Jonathan Gardner
Network Administrator

Quality Health Associates of North Dakota
41 36th Ave NW | Minot, ND 58703
Phone (701) 989-6237 | Fax (701) 857-9755

***@***.******@***.***>

www.qualityhealthnd.org<http://www.qualityhealthnd.org/>



•Check out the events on the North Dakota Healthcare Partners Events Calendar (NDHPEC)<https://www.ndhpec.com/>

________________________________

**Comment by aanunez** [comment]
Resolved with #9
